server:
  name: "gogo_dy_user"
  addr: "0.0.0.0:8081"
redis:
  host: "redis5"
  port: 6379
  password: ""
  db: 0
grpc:
  addr: "0.0.0.0:8881"
  name: "user"
  version: "1.0.0"
  weight: 2
etcd:
  addrs:
    - "111.173.80.63:2379"
mysql:
  username: root
  password: 10086@gogo.com
  host: 127.0.0.1
  port: 3306
  db: gogo_dy