version: '2'
services:
  gogo_dy:
    container_name: 'gogo_dy'
    ports:
      - '8080:8080'
    restart: always
    image: 'liang09255/gogo_dy:v1.0.0'
    volumes:
      - './config.yaml:/app/config.yaml'
    network_mode: 'host'
