mysql:
  username: 
  password: 
  host: 
  port:
  db:

jwtKey:

aliOSS:
  bucket:
  endpoint: 
  accessKeyId:
  accessKeySecret:

passwordSalt:

redis:
  host:
  port:
  password:
  db:

etcd:
  addrs:
    - 

userServer:
  name: 
  addr: 
  port: 
  http: 

chatServer:
  name: 
  addr: 
  port: 
  http: 

videoServer:
  name: 
  addr: 
  port:
  http:
