mysql:
  username: root
  password: password
  host: "mysql8"
#  host: "127.0.0.1"
  port: 3306
  db: gogo_dy

jwtKey: jwtKey

aliOSS:
  bucket: "gogo-dy"
  endpoint: "oss-cn-shenzhen.aliyuncs.com"
  accessKeyId: accessKeyId
  accessKeySecret: accessKeySecret

passwordSalt: passwordSalt

redis:
  host: "redisStack"
#  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0

etcd:
  addrs:
    - "etcd3:2379"
#     - "127.0.0.1:2379"
kafka:
#  addr: "127.0.0.1:9092"
  addr: "kafka:9092"

userServer:
  name: "user"
  addr: "0.0.0.0:8081"
  port: 8081
  http: "0.0.0.0:8082"

chatServer:
  name: "chat"
  addr: "0.0.0.0:8083"
  port: 8083
  http: "0.0.0.0:8084"

videoServer:
  name: "video"
  addr: "0.0.0.0:8085"
  port: 8085
  http: "0.0.0.0:8086"
