# 所有隐私内容全部写在配置文件中
mysql:
  dsn: "root:root@tcp(host:port)/gogo_dy?charset=utf8mb4&parseTime=True&loc=Local"

jwtKey: "jwtKey"

aliOSS:
  bucket: "bucket"
  endpoint: "endpoint"
  accessKeyId: "accessKeyId"
  accessKeySecret: "accessKeySecret"

passwordSalt: "passwordSalt"